import { b } from "@weknow-network/wk-lerna-lib-playground";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          wk-lib-consumer-playground
        </h1>
        <b.Button label="Default" />
        <b.StyledButton label="Styled" primary />
      </main>
    </div>
  );
}
